server:
  port: 8081

spring:
  liquibase:
#    dropFirst: true
    enabled: true
    changeLog: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:mysql://localhost/mydb
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddlAuto: validate
